[package]
name = "schema_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.60", features = ["visit-mut", "extra-traits"] }
proc-macro-error = "1.0.4"