[package]
name = "bits_derive"
version = "0.1.0"
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.60", features = ["extra-traits"] }
quote = "1.0.2"
proc-macro2 = "1.0.24"
